version: '3.8'

services:
  wordpress:
    image: wordpress:latest  # Image officielle de WordPress
    container_name: wordpress
    ports:
      - "8080:80"  # WordPress accessible sur le port 8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html  # Stockage des fichiers WordPress

  db:
    image: mysql:5.7  # Image officielle de MySQL
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql  # Stockage des données MySQL

volumes:
  wordpress_data:
  db_data:

